name: Minecraft Server Keep-Alive

on:
  schedule:
    # Runs every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch: # Allows you to run it manually from the GitHub Actions tab

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run Keep-Alive Script
      env:
        MC_HOST: ${{ secrets.MC_HOST }}
        MC_PORT: ${{ secrets.MC_PORT }}
        MC_USERNAME: ${{ secrets.MC_USERNAME }}
      run: node index.js
      
